# Copyright (c) IBM Corporation 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# tasks file for zmf_cpm_provision_software_service

- name: Instance record directory
  ansible.builtin.include_tasks: instance_dir_util.yml
  run_once: true

# Support input_vars to be provided via playbook. If input_vars isn't set then set default below
- name: Set input_vars as fact
  ansible.builtin.set_fact:
    input_vars: "[]"
  when: input_vars is not defined

- name: Set tenant_name as fact
  ansible.builtin.set_fact:
    tenant_name: "default"
  when: tenant_name is not defined

- name: Set systems_nicknames as fact
  ansible.builtin.set_fact:
    sysnames: '["{{ systems_nicknames }}"]'
  when: systems_nicknames is defined

- name: Set systems_nicknames as fact
  ansible.builtin.set_fact:
    sysnames: "[]"
  when: systems_nicknames is not defined

# Allow zmf_body to be set in previous tasks. If zmf_body isn't set then set default below
- name: Set zmf_body as fact
  ansible.builtin.set_fact:
    zmf_body: '{"domain-name":"{{ domain_name }}","tenant-name":"{{ tenant_name }}",
      "systems-nicknames": {{ sysnames }},"input-variables":{{ input_vars }}}'
  when: zmf_body is not defined

- name: Provision template
  ansible.builtin.uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/provisioning/rest/1.0/psc/{{ cpm_template_name }}/actions/run"
    return_content: true
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    method: POST
    status_code: "200"
    validate_certs: false
    body_format: json
    body: "{{ zmf_body }}"
  delegate_to: localhost
  register: provision_results

- name: Write instance information to disk
  ansible.builtin.copy:
    content: "{{ provision_results.json | to_nice_json(indent=2) }}"
    dest: "{{ instance_record_dir }}/{{ inventory_hostname }}/{{ cpm_template_name }}-{{ provision_results.json['registry-info']['external-name'] }}.json"
    mode: '0644'
  delegate_to: localhost

- name: Display instance record file path
  ansible.builtin.debug:
    msg: "Instance record saved at: {{ instance_record_dir }}/{{ inventory_hostname }}/{{ cpm_template_name }}-\
          {{ provision_results.json['registry-info']['external-name'] }}.json"

##############################################################################
# Verify workflow step status, requires the following variables:
# {{zmf_host:zmf_port}} -> z/OSMF host uri
# {{max_retry}} -> max retry count before task exit with failing status
##############################################################################
- name: Provision instance section
  ansible.builtin.include_tasks: loop_instance_provision_step_state.yml
  vars:
    instance_object_id: "{{ provision_results.json['registry-info']['object-id'] }}"

- name: Set full_instance_json as fact
  ansible.builtin.set_fact:
    full_instance_json: ""

- name: Get provisioned instance information
  ansible.builtin.uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/provisioning/rest/1.0/scr/{{ provision_results.json['registry-info']['object-id'] }}"
    method: GET
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    status_code: "200"
    validate_certs: false
    return_content: true
  register: full_instance_json
  delegate_to: localhost

- name: Update instance information
  block:
    - name: Update fully provisioned instance information to local
      ansible.builtin.copy:
        content: '{ "registry-info" : {{ full_instance_json.json | default("") | to_nice_json(indent=2) }}}'
        dest: "{{ instance_record_dir }}/{{ inventory_hostname }}/{{ cpm_template_name }}-{{ provision_results.json['registry-info']['external-name'] }}.json"
        mode: '0644'
      delegate_to: localhost

    - name: Set variable for instance json file path
      ansible.builtin.set_fact:
        zosmf_instance_info: "{{ full_instance_json.json }}"
        instance_info_json_path: "{{ instance_record_dir }}/{{ inventory_hostname }}/{{ cpm_template_name }}-\
                                  {{ provision_results.json['registry-info']['external-name'] }}.json"

- name: Display instance record file path
  ansible.builtin.debug:
    msg: "Instance record saved at: {{ instance_record_dir }}/{{ inventory_hostname }}/{{ cpm_template_name }}-\
          {{ provision_results.json['registry-info']['external-name'] }}.json"
  run_once: true
