# Copyright (c) IBM Corporation 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# tasks file for zmf_cpm_get_software_instance

- name: Instance record directory
  ansible.builtin.include_tasks: instance_dir_util.yml
  run_once: true

- name: Set instance_data as fact
  ansible.builtin.set_fact:
    instance_data: ""

- name: Get software instance information
  ansible.builtin.uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/provisioning/rest/1.0/scr?external-name={{ external_software_name }}"
    method: GET
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    status_code: "200"
    validate_certs: false
    return_content: true
  register: instance_data
  delegate_to: localhost

- name: Set instance_object_id as fact
  ansible.builtin.set_fact:
    instance_object_id: "{{ instance_data.json['scr-list'][0]['object-id'] }}"


- name: Set full_instance_json as fact
  ansible.builtin.set_fact:
    full_instance_json: ""

- name: Get full software instance information
  ansible.builtin.uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/provisioning/rest/1.0/scr/{{ instance_object_id }}"
    method: GET
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    status_code: "200"
    validate_certs: false
    return_content: true
  register: full_instance_json
  delegate_to: localhost

- name: Update instance information
  block:
    - name: Update fully provisioned instance information to local
      ansible.builtin.copy:
        content: '{ "registry-info" : {{ full_instance_json.json | default("") | to_nice_json(indent=2) }}}'
        dest: "{{ instance_record_dir }}/{{ inventory_hostname }}/{{ external_software_name }}-\
               {{ full_instance_json.json['object-name'] }}.json"
        mode: '0644'
      delegate_to: localhost

    - name: Set variable for instance json file path
      ansible.builtin.set_fact:
        zosmf_instance_info: "{{ full_instance_json.json }}"
        instance_info_json_path: "{{ instance_record_dir }}/{{ inventory_hostname }}/{{ external_software_name }}-\
                                  {{ full_instance_json.json['object-name'] }}.json"

- name: Display instance record file path
  ansible.builtin.debug:
    msg: "Instance record saved at: {{ instance_record_dir }}/{{ inventory_hostname }}/{{ external_software_name }}-\
               {{ full_instance_json.json['object-name'] }}.json"
  run_once: true
