# Copyright (c) IBM Corporation 2025

# IBM collection namespace
namespace: ibm

# Ansible collection to work with z/OS based on z/OSMF
name: ibm_zosmf

# The collection version
version: 1.6.0

# Collection README file
readme: README.md

# Contributors
authors:
  - "Taylor Digilio @TaylorDigilio"
  - "Hiren Shah @shreeji818"
  - "Aaron Kippins @AKippins"

# Description
description: Ansible collection consisting of modules and roles to work with z/OS based on z/OS Management Facility(z/OSMF).

# License
license:
  - Apache-2.0

# Tags
tags:
  - ibm
  - z
  - zos
  - z_os
  - mvs
  - zosmf
  - zos_management_facility
  - zos_workflow
  - zosmf_workflow
  - cloud_provisioning
  - cics_provisioning_template
  - db2_provisioning_template
  - mq_provisioning_template
  - liberty_provisioning_template
  - zosconnect_provisioning_template
  - sca
  - security
  - security_configuration_assistant
  - zos_software_update
  - zos_management_services_catalog

# The URL of the originating SCM repository
repository: https://github.com/IBM/ibm_zosmf

# The URL to any online docs
documentation: https://ibm.github.io/z_ansible_collections_doc/index.html

# The URL to the collection issue tracker
issues: https://github.com/IBM/ibm_zosmf/issues

# Ignore files and directories matching the following patterns
build_ignore:
  - .ansible
  - .ansible-lint
  - .ansible-test-ignore
  - .cache
  - .DS_Store
  - .flake8
  - .git
  - .github
  - .gitignore
  - .idea
  - .pre-commit-config.yaml
  - .python-version
  - .pytest_cache
  - .secrets.baseline
  - .vscode
  - .whitesource
  - meta/context
  - tests/scripts
  - '*.tar.gz'
  - __pycache__
  - Jenkinsfile
  - Jenkinsfile.old
  - ansible.cfg
  - changelogs
  - collections
  - docs
  - importer_result.json
  - test_config.yml
  - tests/*.ini
  - tests/*.py
  - tests/.pytest_cache
  - tests/__pycache__
  - tests/functional
  - tests/helpers
  - tests/requirements.txt
  - tests/unit
  - tests/CICD
  - tests/output
  - tests/sanity/ignore-2.9.txt
  - tests/sanity/ignore-2.10.txt
  - tests/sanity/ignore-2.11.txt
  - tests/sanity/ignore-2.12.txt
  - tests/sanity/ignore-2.13.txt
  - tests/sanity/ignore-2.14.txt
  - venv*
  - ansible_collections
  - '*.log'
  - '*.sh'
  - ac
  - branch_protection_rules.json
