# Copyright (c) IBM Corporation 2025
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# Tasks file for zmf_swmgmt_csi_query play.

# Do not attempt to execute the play without a software instance, a UUID, or a CSI data set name.
- name: A software instance and system nickname, a UUID, or a CSI data set name must be provided to the role
  ansible.builtin.fail:
    msg: "Specify a software instance and system nickname, a UUID, or a CSI data set name and retry the role."
  when: >
    (software_instance_uuid is not defined or software_instance_uuid == '') and (software_instance_name is not defined or software_instance_name == ''
    or system_nickname is not defined or system_nickname == '') and (csi_data_set_name is not defined or csi_data_set_name == '')

# Issue a failure message and stop the playbook if no zones or entries were specified.
- name: Display the CSI Query action failure information if no zones or entries were specified
  ansible.builtin.fail:
    msg: "One or more zones and one or more entries must be specified for the CSI query.  Specify one or more zones and one or more entries and try again."
  when: zones is not defined or entries is not defined

# Do not attempt to execute the play without a CSI query response file.
- name: A CSI query response file must be provided to the role
  ansible.builtin.fail:
    msg: "Specify a CSI query response file and retry the role."
  when: csi_query_response_file is not defined

# Do not attempt to execute the play without a z/OSMF host.
- name: Validate zmf_host is defined and not empty
  ansible.builtin.fail:
    msg: "zmf_host: Specify a z/OSMF host name and retry the role."
  when: zmf_host is not defined or zmf_host == ''

# Create a variable for the csi query response content.
- name: Initialize the container for the csi query response content
  ansible.builtin.set_fact:
    csi_query_response: ""

# Build the CSI query request body.
- name: Build the CSI query request content body
  ansible.builtin.set_fact:
    csi_query_request_body: >-
      {{
        {
          'zones': zones,
          'entries': entries
        }
        | combine(
            (subentries is defined)
            | ternary({'subentries': subentries}, {}),
            recursive=True
          )
        | combine(
            (filter is defined)
            | ternary({'filter': filter}, {}),
            recursive=True
          )
        | combine(
            (remote_zmf_user is defined)
            | ternary({'zosmfuid': remote_zmf_user}, {}),
            recursive=True
          )
        | combine(
            (remote_zmf_password is defined)
            | ternary({'zosmfpw': remote_zmf_password}, {}),
            recursive=True
          )
        | combine(
            (proxy_zmf_user is defined)
            | ternary({'proxyuid': proxy_zmf_user}, {}),
            recursive=True
          )
        | combine(
            (proxy_zmf_password is defined)
            | ternary({'proxypw': proxy_zmf_password}, {}),
            recursive=True
          )
      }}
  no_log: true

# Create and encode the HTTP Request URL with optional port
- name: Create the CSI Query HTTP Request URL
  ansible.builtin.set_fact:
    request_url: >-
      {{
        (zmf_host + (':' + zmf_port|string if zmf_port is defined and ':' not in zmf_host else ''))
        + (
          '/zosmf/swmgmt/csi/csiquery/' + csi_data_set_name if csi_data_set_name is defined
          else '/zosmf/swmgmt/swi/' + software_instance_uuid + '/csiquery' if software_instance_uuid is defined
          else '/zosmf/swmgmt/swi/' + system_nickname + '/' + software_instance_name + '/csiquery'
        )
        | urlencode
      }}

##########################################################################################
# URI MODULE #1: Start a csi query async request for a software instance or data set.    #
##########################################################################################
- name: Querying the global zone CSI data set
  ansible.builtin.uri:
    url: "https://{{ request_url }}"
    return_content: true
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    method: POST
    status_code: 202, 400, 403, 404, 409, 500, 503
    validate_certs: "{{ zmf_validate_certs }}"
    body_format: json
    body: "{{ csi_query_request_body }}"
  delegate_to: localhost
  register: csi_query_response

# Create a variable for the csi query status monitor URL.
- name: Set the csi query status monitor URL
  ansible.builtin.set_fact:
    csi_query_status_monitor_url: "{{ csi_query_response.json['statusurl'] }}"
  when: csi_query_response.status == 202

# Issue a failure message when the request fails.
- name: Display CSI Query REST API failure information
  ansible.builtin.fail:
    msg: >-
      CSI Query REST API failure details:
      {{ csi_query_response.json | default(csi_query_response) }}
  when: csi_query_response.status != 202

###################################################################
# URI MODULE #2: Check the status of the csi query async request. #
###################################################################

# Wait for the asynchronous thread to finish and return a response.
- name: >
    Poll the status monitor URL of the csi query operation every {{ status_retrieval_delay }}
    second(s) until it is finished or maximum {{ status_retrieval_retries }} poll(s) reached
  ansible.builtin.uri:
    url: "{{ csi_query_status_monitor_url }}"
    method: GET
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    status_code: 200
    validate_certs: "{{ zmf_validate_certs }}"
    return_content: true
  register: csi_query_response
  delegate_to: localhost
  # This task's URL will be called repeatedly either until the "until" condition is met (request failed or
  # request completed) or the request still isn't finished after the specified "complete_check_times" attempts.
  until: (csi_query_response is failed) or (csi_query_response.json['status'] == 'complete')
  retries: "{{ status_retrieval_retries }}"
  delay: "{{ status_retrieval_delay }}"

# Save the csi query operation's response in a file.
- name: Write the results for the csi query operation to a JSON file
  block:
    # Perform the copy of the csi query response to the file.
    - name: "Copy the csi query results to JSON file <{{ csi_query_response_file }}>"
      ansible.builtin.copy:
        content: '{{ csi_query_response.json | default("") | to_nice_json(indent=2) }}'
        dest: '{{ csi_query_response_file }}'
        mode: '0644'
      delegate_to: localhost

    # Save the response content into a local variable.
    - name: Create a variable to hold the value of the csi query results
      ansible.builtin.set_fact:
        csi_query_response_json: "{{ csi_query_response.json }}"

# Show the path to the csi query REST API results file.
- name: Display the path to the file containing the results from the csi query operation
  ansible.builtin.debug:
    msg: "Output filename= {{ csi_query_response_file }}"
