# Copyright (c) IBM Corporation 2025
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# Tasks file for zmf_swupdate_cancel play.

# Issue a failure message and stop the playbook if a software instance/system nickname, UUID, or process ID specified.
- name: A software instance and system nickname, a UUID, or a software update process ID must be provided to the role
  ansible.builtin.fail:
    msg: "Specify a software instance and system nickname, a UUID, or a software update process ID and retry the role."
  when: >
    (software_instance_uuid is not defined or software_instance_uuid == '') and (software_instance_name is not defined or software_instance_name == ''
    or system_nickname is not defined or system_nickname == '') and (swupdate_process_id is not defined or swupdate_process_id == '')

# Do not attempt to execute the play without a z/OSMF host.
- name: Validate zmf_host is defined and not empty
  ansible.builtin.fail:
    msg: "zmf_host: Specify a z/OSMF host name and retry the role."
  when: zmf_host is not defined or zmf_host == ''

# Create a variable for the cancel software update response content.
- name: Initialize the container for the cancel software update response content
  ansible.builtin.set_fact:
    swupdate_cancel_response: ""

# Create and encode the HTTP Request URL with optional port
- name: Create the HTTP Request URL
  ansible.builtin.set_fact:
    request_url: >-
      {{ (zmf_host + (':' + zmf_port|string if zmf_port is defined and ':' not in zmf_host else ''))
      + (
        '/zosmf/swmgmt/swupdate/cancel/' + swupdate_process_id if swupdate_process_id is defined
        else '/zosmf/swmgmt/swi/' + software_instance_uuid + '/swupdate/cancel' if software_instance_uuid is defined
        else '/zosmf/swmgmt/swi/' + system_nickname + '/' + software_instance_name + '/swupdate/cancel'
      )
      | urlencode }}

###################################################################
# URI MODULE #1: Cancel the software update process.              #
###################################################################
- name: Cancel the software update process
  ansible.builtin.uri:
    url: "https://{{ request_url }}"
    method: POST
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    status_code: 200, 400, 403, 404, 409, 500, 503
    validate_certs: "{{ zmf_validate_certs }}"
    return_content: true
  register: swupdate_cancel_response
  delegate_to: localhost

# Create a variable for the software update process ID.
- name: Set the software update process ID
  ansible.builtin.set_fact:
    swupdate_process_id: "{{ swupdate_cancel_response.json['processid'] }}"
  when: swupdate_cancel_response.status == 200

# Issue a failure message when the request fails.
- name: Display Cancel Software Update REST API failure information
  ansible.builtin.fail:
    msg: >-
      Cancel Software Update REST API failure details:
      {{ swupdate_cancel_response.json | default(swupdate_cancel_response) }}
  when: swupdate_cancel_response.status != 200
