# Copyright (c) IBM Corporation 2021
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# tasks file for zmf_cpm_list_software_templates

- name: Instance record directory
  ansible.builtin.include_tasks: instance_dir_util.yml
  run_once: true

- name: "List published provisioning templates"
  ansible.builtin.uri:
    url: "https://{{ zmf_host }}:{{ zmf_port }}/zosmf/provisioning/rest/1.0/psc/"
    user: "{{ zmf_user | trim }}"
    password: "{{ zmf_password | trim }}"
    force_basic_auth: true
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    method: GET
    status_code: "200"
    validate_certs: false
    return_content: true
  delegate_to: localhost
  register: list_results

- name: Update instance information
  block:
    - name: Update fully provisioned instance information to local
      ansible.builtin.copy:
        content: '{{ list_results.json | default("") | to_nice_json(indent=2) }}'
        dest: "{{ instance_record_dir }}/{{ inventory_hostname }}/Published_Templates_List.json"
        mode: '0644'
      delegate_to: localhost

    - name: Set variable for template info json file path
      ansible.builtin.set_fact:
        template_info_json_path: "{{ instance_record_dir }}/{{ inventory_hostname }}/\
                                  Published_Templates_List.json"

- name: Display template record file path
  ansible.builtin.debug:
    msg: "Published template list saved at:
     {{ instance_record_dir }}/{{ inventory_hostname }}/Published_Templates_List.json"
  run_once: true
