# Copyright (c) IBM Corporation 2025, 2026
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

---
# Tasks file for zmf_swupdate_resume play.

# Do not attempt to execute the play without a software instance/system nickname, UUID, or process ID specified.
- name: A software instance and system nickname, a UUID, or a software update process ID must be provided to the role
  ansible.builtin.fail:
    msg: "Specify a software instance and system nickname, a UUID, or a software update process ID and retry the role."
  when: >
    (software_instance_uuid is not defined or software_instance_uuid == '') and
    (software_instance_name is not defined or software_instance_name == '' or
    system_nickname is not defined or system_nickname == '') and
    (swupdate_process_id is not defined or swupdate_process_id == '')

# Do not attempt to execute the play without a z/OSMF host.
- name: Validate zmf_host is defined and not empty
  ansible.builtin.fail:
    msg: "zmf_host: Specify a z/OSMF host name and retry the role."
  when: zmf_host is not defined or zmf_host == ''

# Create a variable for the resume software update response content.
- name: Initialize the container for the resume software update response content
  ansible.builtin.set_fact:
    swupdate_resume_response: ""

# Build the resume software update request body.
- name: Build the resume software update request content body
  ansible.builtin.set_fact:
    swupdate_resume_request_body: >-
      {{
        {}
        | combine(
            (suspend_steps is defined)
            | ternary({'suspend-steps': suspend_steps}, {}),
            recursive=True
          )
        | combine(
            (exclude_updates is defined)
            | ternary({'exclude-updates': exclude_updates}, {}),
            recursive=True
          )
        | combine(
            (resolve_holds is defined)
            | ternary({'resolve-holds': resolve_holds}, {}),
            recursive=True
          )
        | combine(
            (smpe_userid is defined)
            | ternary({'smpe-userid': smpe_userid}, {}),
            recursive=True
          )
        | combine(
            (notes is defined)
            | ternary({'notes': notes}, {}),
            recursive=True
          )
        | combine(
            (remote_zmf_user is defined)
            | ternary({'zosmfuid': remote_zmf_user}, {}),
            recursive=True
          )
        | combine(
            (remote_zmf_password is defined)
            | ternary({'zosmfpw': remote_zmf_password}, {}),
            recursive=True
          )
        | combine(
            (proxy_zmf_user is defined)
            | ternary({'proxyuid': proxy_zmf_user}, {}),
            recursive=True
          )
        | combine(
            (proxy_zmf_password is defined)
            | ternary({'proxypw': proxy_zmf_password}, {}),
            recursive=True
          )
      }}
  no_log: true

# Ensure there is a colon in the host. Add the z/OSMF server port if specified.
- name: "Set the zmf_port if specified"
  ansible.builtin.set_fact:
    zmf_host: '{{ zmf_host }}:{{ zmf_port }}'
  when: zmf_port is defined and ':' not in zmf_host

# Using Software Update Process ID.
- name: Create the HTTP Request URL
  ansible.builtin.set_fact:
    request_url: "{{ zmf_host }}/zosmf/swmgmt/swupdate/resume/{{ swupdate_process_id }}"
  when: swupdate_process_id is defined

# Using Software Instance UUID.
- name: Create the HTTP Request URL
  ansible.builtin.set_fact:
    request_url: "{{ zmf_host }}/zosmf/swmgmt/swi/{{ software_instance_uuid }}/swupdate/resume"
  when: swupdate_process_id is not defined and software_instance_uuid is defined

# Using Software Instance Name and System.
- name: Create the HTTP Request URL
  ansible.builtin.set_fact:
    request_url: "{{ zmf_host }}/zosmf/swmgmt/swi/{{ system_nickname }}/{{ software_instance_name }}/swupdate/resume"
  when: swupdate_process_id is not defined and software_instance_uuid is not defined and software_instance_name is defined

# Encode the HTTP request URL
- name: Encode the request URL
  ansible.builtin.set_fact:
    request_url: "{{ request_url | urlencode }}"

##########################################################################################
# URI MODULE #1: Resume a software update for a software instance.                       #
##########################################################################################
- name: Resume the software update process
  ansible.builtin.uri:
    url: "https://{{ request_url }}"
    return_content: true
    user: "{{ zmf_user | trim if zmf_user is defined else omit }}"
    password: "{{ zmf_password | trim if zmf_password is defined else omit }}"
    force_basic_auth: "{{ true if zmf_user is defined else omit }}"
    client_cert: "{{ zmf_client_cert | default(omit) }}"
    client_key: "{{ zmf_client_key | default(omit) }}"
    headers:
      Host: "{{ zmf_host }}"
      Origin: "https://{{ zmf_host }}"
    method: POST
    status_code: 202, 400, 403, 404, 409, 500, 503
    validate_certs: "{{ zmf_validate_certs }}"
    body_format: json
    body: "{{ swupdate_resume_request_body }}"
  delegate_to: localhost
  register: swupdate_resume_response

# Create a variable for the software update process ID.
- name: Set the software update process ID
  ansible.builtin.set_fact:
    swupdate_process_id: "{{ swupdate_resume_response.json['processid'] }}"
  when: swupdate_resume_response.status == 202

# Issue a failure message when the request fails.
- name: Display Resume Software Update REST API failure information
  ansible.builtin.fail:
    msg: >-
      Resume Software Update REST API failure details:
      {{ swupdate_resume_response.json | default(swupdate_resume_response) }}
  when: swupdate_resume_response.status != 202
